/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.notepad;

import java.awt.Component;
import java.awt.event.*;
import java.io.*;
import java.nio.file.*;
import javax.swing.*;
import javax.swing.JFileChooser;

/**
 * @author Agus
 */

public class MainJFrame extends javax.swing.JFrame {
   
    private File file;
    
    public MainJFrame() {
        initComponents();
        myInit();
    }
    
    public void myInit() {
        setLocationRelativeTo(null);
        setTitle("Notepad");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jToolBar = new javax.swing.JToolBar();
        jButton3 = new javax.swing.JButton();
        jButtonOpen = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuOpen = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItemExit = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));

        jToolBar.setRollover(true);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/160476.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("properties/Bundle_es_ES"); // NOI18N
        jButton3.setText(bundle.getString("MainJFrame.jButton3.text")); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar.add(jButton3);

        jButtonOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3344056.png"))); // NOI18N
        jButtonOpen.setText(bundle.getString("MainJFrame.jButtonOpen.text")); // NOI18N
        jButtonOpen.setFocusable(false);
        jButtonOpen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonOpen);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12621403.png"))); // NOI18N
        jButton2.setText(bundle.getString("MainJFrame.jButton2.text")); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar.add(jButton2);

        getContentPane().add(jToolBar, java.awt.BorderLayout.PAGE_START);

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu.setText(bundle.getString("MainJFrame.jMenu.text")); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/160476.png"))); // NOI18N
        jMenuItem1.setText(bundle.getString("MainJFrame.jMenuItem1.text")); // NOI18N
        jMenu.add(jMenuItem1);

        jMenuOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3344056.png"))); // NOI18N
        jMenuOpen.setText(bundle.getString("MainJFrame.jMenuOpen.text")); // NOI18N
        jMenuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOpenActionPerformed(evt);
            }
        });
        jMenu.add(jMenuOpen);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText(bundle.getString("MainJFrame.jCheckBoxMenuItem1.text")); // NOI18N
        jCheckBoxMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12621403.png"))); // NOI18N
        jMenu.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText(bundle.getString("MainJFrame.jCheckBoxMenuItem3.text")); // NOI18N
        jCheckBoxMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save As.png"))); // NOI18N
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        jMenu.add(jCheckBoxMenuItem3);
        jMenu.add(jSeparator1);

        jCheckBoxMenuItemExit.setSelected(true);
        jCheckBoxMenuItemExit.setText(bundle.getString("MainJFrame.jCheckBoxMenuItemExit.text")); // NOI18N
        jCheckBoxMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jCheckBoxMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemExitActionPerformed(evt);
            }
        });
        jMenu.add(jCheckBoxMenuItemExit);

        jMenuBar.add(jMenu);

        jMenu2.setText(bundle.getString("MainJFrame.jMenu2.text")); // NOI18N
        jMenuBar.add(jMenu2);

        jMenu3.setText(bundle.getString("MainJFrame.jMenu3.text")); // NOI18N
        jMenuBar.add(jMenu3);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jCheckBoxMenuItemExitActionPerformed

    private void jButtonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenActionPerformed
        load();
    }//GEN-LAST:event_jButtonOpenActionPerformed

    private void jMenuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOpenActionPerformed
        load();
    }//GEN-LAST:event_jMenuOpenActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
        
    }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed

     
    /**
     * @param args the command line arguments
     */
    
    
    
    private void load() {
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = chooser.getSelectedFile();
            try {
                openFile(file);
            } catch(IOException ex) {
               JOptionPane.showConfirmDialog(this, 
                       "Error reading file" + file.getName(),
                       "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void openFile(File file) throws IOException {
        BufferedReader input = null;
        String fileType = Files.probeContentType(Path.of(file.getAbsolutePath()));
        if (!fileType.equals("text/plain")) {
            throw new IOException("Not a text file");
        }
        try {
            input = new BufferedReader(new FileReader(file));
            String line;
            String text = "";
            while ((line = input.readLine()) != null) {
                text += line + "\n";
            }
            jTextArea.setText(text);
            setTitle(file.getName());
        } finally {
            if (input != null) {
                input.close();
            }
            
        }
    }
    
    /*
    private void saveFile(File file) throws IOException {
        JFileChooser fileChooser = new JFileChooser();
        Component modalToComponent = null;
        if (fileChooser.showSaveDialog(modalToComponent) == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        }
    }
    */
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonOpen;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemExit;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuOpen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JToolBar jToolBar;
    // End of variables declaration//GEN-END:variables
}
